# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arrow.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'arrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import line_pb2 as line__pb2
from . import mesh_pb2 as mesh__pb2
from . import xform_pb2 as xform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rrow.proto\x12\rsession_proto\x1a\nline.proto\x1a\nmesh.proto\x1a\x0bxform.proto\"\x9e\x01\n\x05\x41rrow\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06radius\x18\x03 \x01(\x01\x12!\n\x04line\x18\x04 \x01(\x0b\x32\x13.session_proto.Line\x12!\n\x04mesh\x18\x05 \x01(\x0b\x32\x13.session_proto.Mesh\x12#\n\x05xform\x18\x06 \x01(\x0b\x32\x14.session_proto.Xformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARROW']._serialized_start=68
  _globals['_ARROW']._serialized_end=226
# @@protoc_insertion_point(module_scope)
