# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boundingbox.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'boundingbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import point_pb2 as point__pb2
from . import vector_pb2 as vector__pb2
from . import xform_pb2 as xform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62oundingbox.proto\x12\rsession_proto\x1a\x0bpoint.proto\x1a\x0cvector.proto\x1a\x0bxform.proto\"\x93\x02\n\x0b\x42oundingBox\x12$\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x14.session_proto.Point\x12%\n\x06x_axis\x18\x02 \x01(\x0b\x32\x15.session_proto.Vector\x12%\n\x06y_axis\x18\x03 \x01(\x0b\x32\x15.session_proto.Vector\x12%\n\x06z_axis\x18\x04 \x01(\x0b\x32\x15.session_proto.Vector\x12(\n\thalf_size\x18\x05 \x01(\x0b\x32\x15.session_proto.Vector\x12\x0c\n\x04guid\x18\x06 \x01(\t\x12\x0c\n\x04name\x18\x07 \x01(\t\x12#\n\x05xform\x18\x08 \x01(\x0b\x32\x14.session_proto.Xformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boundingbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=77
  _globals['_BOUNDINGBOX']._serialized_end=352
# @@protoc_insertion_point(module_scope)
