# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bvh.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bvh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import boundingbox_pb2 as boundingbox__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbvh.proto\x12\rsession_proto\x1a\x11\x62oundingbox.proto\"Q\n\x07\x42vhAABB\x12\n\n\x02\x63x\x18\x01 \x01(\x01\x12\n\n\x02\x63y\x18\x02 \x01(\x01\x12\n\n\x02\x63z\x18\x03 \x01(\x01\x12\n\n\x02hx\x18\x04 \x01(\x01\x12\n\n\x02hy\x18\x05 \x01(\x01\x12\n\n\x02hz\x18\x06 \x01(\x01\"k\n\x07\x42VHNode\x12\x12\n\nleft_index\x18\x01 \x01(\x05\x12\x13\n\x0bright_index\x18\x02 \x01(\x05\x12\x11\n\tobject_id\x18\x03 \x01(\x05\x12$\n\x04\x61\x61\x62\x62\x18\x04 \x01(\x0b\x32\x16.session_proto.BvhAABB\"\x9b\x01\n\x03\x42VH\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x05nodes\x18\x03 \x03(\x0b\x32\x16.session_proto.BVHNode\x12\x12\n\nroot_index\x18\x04 \x01(\x05\x12\x12\n\nworld_size\x18\x05 \x01(\x01\x12)\n\x05\x62oxes\x18\x06 \x03(\x0b\x32\x1a.session_proto.BoundingBoxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bvh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BVHAABB']._serialized_start=47
  _globals['_BVHAABB']._serialized_end=128
  _globals['_BVHNODE']._serialized_start=130
  _globals['_BVHNODE']._serialized_end=237
  _globals['_BVH']._serialized_start=240
  _globals['_BVH']._serialized_end=395
# @@protoc_insertion_point(module_scope)
