# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: elementfeature.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'elementfeature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65lementfeature.proto\x12\rsession_proto\"\xdc\x01\n\x13\x43rossElementFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x18\n\x10\x66\x61\x63\x65_ids_a_first\x18\x02 \x01(\x05\x12\x19\n\x11\x66\x61\x63\x65_ids_a_second\x18\x03 \x01(\x05\x12\x18\n\x10\x66\x61\x63\x65_ids_b_first\x18\x04 \x01(\x05\x12\x19\n\x11\x66\x61\x63\x65_ids_b_second\x18\x05 \x01(\x05\x12\x17\n\x0fjoint_area_guid\x18\x06 \x01(\t\x12\x1a\n\x12joint_volume_guids\x18\x07 \x03(\t\x12\x18\n\x10joint_line_guids\x18\x08 \x03(\t\"a\n\x12\x46\x61\x63\x65\x45lementFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x11\n\tface_id_a\x18\x02 \x01(\x05\x12\x11\n\tface_id_b\x18\x03 \x01(\x05\x12\x17\n\x0fjoint_area_guid\x18\x04 \x01(\t\"v\n\x12\x41xisElementFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x13\n\x0b\x61xis_a_guid\x18\x02 \x01(\t\x12\x13\n\x0b\x61xis_b_guid\x18\x03 \x01(\t\x12\x16\n\x0e\x63onnector_guid\x18\x04 \x01(\t\x12\x10\n\x08\x64istance\x18\x05 \x01(\x01\"5\n\x17\x43ollisionElementFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\xf7\x01\n\x12\x45\x64geElementFeature\x12\x33\n\x05\x63ross\x18\x01 \x01(\x0b\x32\".session_proto.CrossElementFeatureH\x00\x12\x31\n\x04\x66\x61\x63\x65\x18\x02 \x01(\x0b\x32!.session_proto.FaceElementFeatureH\x00\x12\x31\n\x04\x61xis\x18\x03 \x01(\x0b\x32!.session_proto.AxisElementFeatureH\x00\x12;\n\tcollision\x18\x04 \x01(\x0b\x32&.session_proto.CollisionElementFeatureH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'elementfeature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CROSSELEMENTFEATURE']._serialized_start=40
  _globals['_CROSSELEMENTFEATURE']._serialized_end=260
  _globals['_FACEELEMENTFEATURE']._serialized_start=262
  _globals['_FACEELEMENTFEATURE']._serialized_end=359
  _globals['_AXISELEMENTFEATURE']._serialized_start=361
  _globals['_AXISELEMENTFEATURE']._serialized_end=479
  _globals['_COLLISIONELEMENTFEATURE']._serialized_start=481
  _globals['_COLLISIONELEMENTFEATURE']._serialized_end=534
  _globals['_EDGEELEMENTFEATURE']._serialized_start=537
  _globals['_EDGEELEMENTFEATURE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
