# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encoders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ncoders.proto\x12\rsession_proto\"R\n\x0e\x45ncoderOptions\x12\x0e\n\x06pretty\x18\x01 \x01(\x08\x12\x0e\n\x06indent\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x10\n\x08\x63ompress\x18\x04 \x01(\x08\"m\n\x0eSerializedData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12.\n\x07options\x18\x03 \x01(\x0b\x32\x1d.session_proto.EncoderOptions\x12\x0f\n\x07version\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encoders_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCODEROPTIONS._serialized_start=33
  _ENCODEROPTIONS._serialized_end=115
  _SERIALIZEDDATA._serialized_start=117
  _SERIALIZEDDATA._serialized_end=226
# @@protoc_insertion_point(module_scope)
