# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfeature.proto\x12\rsession_proto\"\xd5\x01\n\x0c\x43rossFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x18\n\x10\x66\x61\x63\x65_ids_a_first\x18\x02 \x01(\x05\x12\x19\n\x11\x66\x61\x63\x65_ids_a_second\x18\x03 \x01(\x05\x12\x18\n\x10\x66\x61\x63\x65_ids_b_first\x18\x04 \x01(\x05\x12\x19\n\x11\x66\x61\x63\x65_ids_b_second\x18\x05 \x01(\x05\x12\x17\n\x0fjoint_area_guid\x18\x06 \x01(\t\x12\x1a\n\x12joint_volume_guids\x18\x07 \x03(\t\x12\x18\n\x10joint_line_guids\x18\x08 \x03(\t\"Z\n\x0b\x46\x61\x63\x65\x46\x65\x61ture\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x11\n\tface_id_a\x18\x02 \x01(\x05\x12\x11\n\tface_id_b\x18\x03 \x01(\x05\x12\x17\n\x0fjoint_area_guid\x18\x04 \x01(\t\"o\n\x0b\x41xisFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x13\n\x0b\x61xis_a_guid\x18\x02 \x01(\t\x12\x13\n\x0b\x61xis_b_guid\x18\x03 \x01(\t\x12\x16\n\x0e\x63onnector_guid\x18\x04 \x01(\t\x12\x10\n\x08\x64istance\x18\x05 \x01(\x01\".\n\x10\x43ollisionFeature\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"\xd4\x01\n\x0b\x45\x64geFeature\x12,\n\x05\x63ross\x18\x01 \x01(\x0b\x32\x1b.session_proto.CrossFeatureH\x00\x12*\n\x04\x66\x61\x63\x65\x18\x02 \x01(\x0b\x32\x1a.session_proto.FaceFeatureH\x00\x12*\n\x04\x61xis\x18\x03 \x01(\x0b\x32\x1a.session_proto.AxisFeatureH\x00\x12\x34\n\tcollision\x18\x04 \x01(\x0b\x32\x1f.session_proto.CollisionFeatureH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CROSSFEATURE']._serialized_start=33
  _globals['_CROSSFEATURE']._serialized_end=246
  _globals['_FACEFEATURE']._serialized_start=248
  _globals['_FACEFEATURE']._serialized_end=338
  _globals['_AXISFEATURE']._serialized_start=340
  _globals['_AXISFEATURE']._serialized_end=451
  _globals['_COLLISIONFEATURE']._serialized_start=453
  _globals['_COLLISIONFEATURE']._serialized_end=499
  _globals['_EDGEFEATURE']._serialized_start=502
  _globals['_EDGEFEATURE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
