# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_encoders.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'file_encoders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_encoders.proto\x12\rsession_proto\"R\n\x0e\x45ncoderOptions\x12\x0e\n\x06pretty\x18\x01 \x01(\x08\x12\x0e\n\x06indent\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x10\n\x08\x63ompress\x18\x04 \x01(\x08\"m\n\x0eSerializedData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12.\n\x07options\x18\x03 \x01(\x0b\x32\x1d.session_proto.EncoderOptions\x12\x0f\n\x07version\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_encoders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEROPTIONS']._serialized_start=38
  _globals['_ENCODEROPTIONS']._serialized_end=120
  _globals['_SERIALIZEDDATA']._serialized_start=122
  _globals['_SERIALIZEDDATA']._serialized_end=231
# @@protoc_insertion_point(module_scope)
