# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import vertex_pb2 as vertex__pb2
from . import edge_pb2 as edge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\rsession_proto\x1a\x0cvertex.proto\x1a\nedge.proto\"\xef\x01\n\x05Graph\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04guid\x18\x02 \x01(\t\x12\x34\n\x08vertices\x18\x03 \x03(\x0b\x32\".session_proto.Graph.VerticesEntry\x12\"\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x13.session_proto.Edge\x12\x14\n\x0cvertex_count\x18\x05 \x01(\x05\x12\x12\n\nedge_count\x18\x06 \x01(\x05\x1a\x46\n\rVerticesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.session_proto.Vertex:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPH_VERTICESENTRY']._loaded_options = None
  _globals['_GRAPH_VERTICESENTRY']._serialized_options = b'8\001'
  _globals['_GRAPH']._serialized_start=57
  _globals['_GRAPH']._serialized_end=296
  _globals['_GRAPH_VERTICESENTRY']._serialized_start=226
  _globals['_GRAPH_VERTICESENTRY']._serialized_end=296
# @@protoc_insertion_point(module_scope)
