# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: line.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'line.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import point_pb2 as point__pb2
from . import xform_pb2 as xform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nline.proto\x12\rsession_proto\x1a\x0bpoint.proto\x1a\x0bxform.proto\"\x8f\x01\n\x04Line\x12#\n\x05start\x18\x01 \x01(\x0b\x32\x14.session_proto.Point\x12!\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x14.session_proto.Point\x12\x0c\n\x04guid\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12#\n\x05xform\x18\x05 \x01(\x0b\x32\x14.session_proto.Xformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'line_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINE']._serialized_start=56
  _globals['_LINE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
