# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nurbscurve.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'nurbscurve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import color_pb2 as color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nurbscurve.proto\x12\rsession_proto\x1a\x0b\x63olor.proto\"\x8f\x02\n\nNurbsCurve\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\x12\x13\n\x0bis_rational\x18\x04 \x01(\x08\x12\r\n\x05order\x18\x05 \x01(\x05\x12\x10\n\x08\x63v_count\x18\x06 \x01(\x05\x12\x11\n\tcv_stride\x18\x07 \x01(\x05\x12\x12\n\nnurbsknots\x18\x08 \x03(\x01\x12\x0b\n\x03\x63vs\x18\t \x03(\x01\x12\r\n\x05width\x18\n \x01(\x01\x12)\n\x0bpointcolors\x18\x0b \x03(\x0b\x32\x14.session_proto.Color\x12(\n\nlinecolors\x18\r \x03(\x0b\x32\x14.session_proto.ColorJ\x04\x08\x0c\x10\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nurbscurve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NURBSCURVE']._serialized_start=49
  _globals['_NURBSCURVE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
