# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nurbssurface.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import color_pb2 as color__pb2
from . import xform_pb2 as xform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12nurbssurface.proto\x12\rsession_proto\x1a\x0b\x63olor.proto\x1a\x0bxform.proto\"\xd5\x02\n\x0cNurbsSurface\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\x12\x13\n\x0bis_rational\x18\x04 \x01(\x08\x12\x0f\n\x07order_u\x18\x05 \x01(\x05\x12\x0f\n\x07order_v\x18\x06 \x01(\x05\x12\x12\n\ncv_count_u\x18\x07 \x01(\x05\x12\x12\n\ncv_count_v\x18\x08 \x01(\x05\x12\x13\n\x0b\x63v_stride_u\x18\t \x01(\x05\x12\x13\n\x0b\x63v_stride_v\x18\n \x01(\x05\x12\x0f\n\x07knots_u\x18\x0b \x03(\x01\x12\x0f\n\x07knots_v\x18\x0c \x03(\x01\x12\x0b\n\x03\x63vs\x18\r \x03(\x01\x12\r\n\x05width\x18\x0e \x01(\x01\x12*\n\x0csurfacecolor\x18\x0f \x01(\x0b\x32\x14.session_proto.Color\x12#\n\x05xform\x18\x10 \x01(\x0b\x32\x14.session_proto.Xformb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nurbssurface_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NURBSSURFACE._serialized_start=64
  _NURBSSURFACE._serialized_end=405
# @@protoc_insertion_point(module_scope)
