# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sheet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sheet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsheet.proto\x12\rsession_proto\"\xb2\x01\n\x05Sheet\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x06\x63oords\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x12\n\x06\x63olors\x18\x04 \x03(\x07\x42\x02\x10\x01\x12\x12\n\x06widths\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x15\n\rsegment_count\x18\x06 \x01(\r\x12\x14\n\x0c\x65ntity_count\x18\x07 \x01(\r\x12\x0c\n\x04meta\x18\x08 \x01(\t\x12\x16\n\nsource_ids\x18\x0f \x03(\x07\x42\x02\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sheet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHEET'].fields_by_name['coords']._loaded_options = None
  _globals['_SHEET'].fields_by_name['coords']._serialized_options = b'\020\001'
  _globals['_SHEET'].fields_by_name['colors']._loaded_options = None
  _globals['_SHEET'].fields_by_name['colors']._serialized_options = b'\020\001'
  _globals['_SHEET'].fields_by_name['widths']._loaded_options = None
  _globals['_SHEET'].fields_by_name['widths']._serialized_options = b'\020\001'
  _globals['_SHEET'].fields_by_name['source_ids']._loaded_options = None
  _globals['_SHEET'].fields_by_name['source_ids']._serialized_options = b'\020\001'
  _globals['_SHEET']._serialized_start=31
  _globals['_SHEET']._serialized_end=209
# @@protoc_insertion_point(module_scope)
