# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tolerance.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tolerance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftolerance.proto\x12\rsession_proto\"\xad\x01\n\tTolerance\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x10\n\x08\x61\x62solute\x18\x02 \x01(\x01\x12\x10\n\x08relative\x18\x03 \x01(\x01\x12\x0f\n\x07\x61ngular\x18\x04 \x01(\x01\x12\x15\n\rapproximation\x18\x05 \x01(\x01\x12\x11\n\tprecision\x18\x06 \x01(\x05\x12\x18\n\x10lineardeflection\x18\x07 \x01(\x01\x12\x19\n\x11\x61ngulardeflection\x18\x08 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tolerance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOLERANCE']._serialized_start=35
  _globals['_TOLERANCE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
