# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import treenode_pb2 as treenode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntree.proto\x12\rsession_proto\x1a\x0etreenode.proto\"I\n\x04Tree\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x04root\x18\x03 \x01(\x0b\x32\x17.session_proto.TreeNodeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tree_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TREE._serialized_start=45
  _TREE._serialized_end=118
# @@protoc_insertion_point(module_scope)
